### ISSUE TITLE
Student profile form

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#1]
Get the student profile form from nlc_attendance repo (special branch) and bring it into this repo.
Also put nlc_attendance repos pageTop and pageBottom templates into the sails layout file.

**Comment by ricardmc99** [comment]
🍅

**Comment by smattingly** [comment]
@ricardmc99 This is the stuff that I suggested for removal. It was intended to allow us to place an announcement at the top of every page in the app: "System going down for maintenance at 5 pm" for example. But we have never used it.

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 I try to lift sails and I have this error message: 
```

 info: Starting app...

2--------------------------------------------------------------------------------
 Excuse my interruption, but it looks like this app
 does not have a "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)

 Tired of seeing this prompt?  Edit config/models.js.

 In a production environment (NODE_ENV=production) Sails always uses
 migrate:'safe' to protect against inadvertent deletion of your data.
 But during development, you have a few different options:

 1. FOR DEV:      alter   wipe/drop and try to re-insert ALL my data (recommended)
 2. FOR TESTS:    drop    wipe/drop ALL my data every time I lift Sails
 3. FOR STAGING:  safe    don't auto-migrate my data. I will do it myself

 Read more: sailsjs.com/docs/concepts/models-and-orm/model-settings#?migrate
--------------------------------------------------------------------------------

What would you like Sails to do this time?
 ** NEVER CHOOSE "alter" or "drop" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:  2
--------------------------------------------------------------------------------
 OK!  Temporarily using migrate:'drop'...
 To skip this prompt in the future, edit config/models.js.
--------------------------------------------------------------------------------

 info: ·• Auto-migrating...  (drop)
(node:7378) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:7378) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
 info:  ✓ Auto-migration complete.


error: Server failed to start.
error: (received error: EADDRINUSE)
error: 
error: Troubleshooting tips:
error: 
error:  -> Is something else already running on port 8080 ?
error: 
error:  -> Are you deploying on a platform that requires an explicit hostname, like OpenShift?
error:     (Try setting the `explicitHost` config to the hostname where the server will be accessible.)
error:     (e.g. `mydomain.com` or `183.24.244.42`)
```
I tried to start it in safe mode and I have the same.

**Comment by ricardmc99** [comment]
My last commit on my wip-ricard branch I changed some things inside [studentModels.js](https://github.com/dewv/nlcAttendance/blob/wip-ricard/furl/studentModel.js) in furl. I don't know if they are correct or not. 
1. Line 18 & 35 I have a warning of ClassRank not defined
2. Line 35 I'm not sure I'm calling right the findOne() function

Do you want me to do a pull request to master and you can see all the things I changed?

**Comment by smattingly** [comment]
The warning is because the eslint code checking tool cannot tell where the class is defined. Because sails does not use explicit `require`s for these things, that's the way it is. There is a comment at the bottom of the file that tells eslint to suppress that warning for similar symbols; you can add your class name to the list to eliminate the warning. Longer term, there is a way to put those symbols in one central file, but I'm not there yet.

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 I'm trying to add some JS to the [studentForm.htlm](https://github.com/dewv/nlcAttendance/blob/wip-ricard/views/pages/studentForm.html). I want that the user press yes to the button of "Do you play any Sport" and then the option to choose the fall or the spring appears. I know the JS that I wrote probably doesn't go there but where should I put a studentForm.js file and then export it to the HTML

**Comment by ricardmc99** [comment]
Just change it. I add a file under assets/js

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 Trying to add an icon to the layout html

**Comment by ricardmc99** [comment]
🍅 Add Jquery to the code. I can't make it work, but I don't get and error.

**Comment by smattingly** [comment]
@ricardmc99 Sorry I didn't catch this sooner. I hate to discourage creative experiments, but in a professional environment, we need to give priority to things that the yield (most) value for the organization. So we need a complete working form, and it's better not to spend time on the dynamic display behavior. 

Also, design decisions like that need to be made as a group, especially when they require bringing in a new client-side library like jQuery.

To try to meet you halfway, I'll say this. Feel free to try this out, but do it on a separate branch with the understanding that it might (probably) won't get merged into master. And the work should be on "your own time" not on "company time".
