### ISSUE TITLE
Implement infinite scrolling for visit list

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#150]
(The original description is preserved at the bottom of this comment. Some of it was inaccurate or not relevant, so I'm taking another crack at it.)

We need to speed up the loading of the visit list page, which is the default page to show to staff users. It has become slow now that there are a few hundred visits stored in the free-tier cloud database.

- [x] Modify the current setup so that the page loads with only the N most recent visit records. (We will experiment to find a good value for N.)
- [x] Add client-side [onscroll event handler](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onscroll3); when user scrolls close to bottom of table, trigger ...
- [ ] client side code that uses [AJAX](https://www.w3schools.com/xml/ajax_intro.asp) to fetch the _next_ N most recent records, and append them to the table.
- [ ] Extend the API to support that AJAX request: process query string "skip number" and return JSON. So for example, `GET /visit?skip=MN&count=N` would return N records of *JSON* format data, starting with record M*N+1.

--------------------------------------
*archive of original description*

Because we are seeing slow database retrieval, let's add "Infinite scrolling" to speed up the visit list screen.

First, let's distinguish two possible approaches to doing this.
1. When the page loads, *all* of the data is fetched (like now) *but* the page display does not wait for the fetch to finish. The page is drawn right away, with the first chunk of records, while the rest of the records are still being fetched in the background. These other records can be added to the DOM (put into the page) in one of two ways: automatically, as they are available, or b) a chunk at a time if/when the user scrolls to (almost) the last currently displayed record.
2. In this approach, the visible behavior will be like 1b above. The difference is that the data is actually fetched in chunks: only the first chunk at page load, and each additional chunk when needed because the user is scrolling down far enough.

Approach 1 will require some study of details in how pages load and are drawn-- what events do/don't hold up drawing, and leveraging that knowledge. I think this is doable, adding client-side JS to the page and tweaking some HTML. The findthemasks.com site does this, or did.

Approach 2 will also require client-side JS and HTML changes, but in addition we will have to extend our API. Right now, the only way to fetch visit data from the server is embedded within the HTML page in question. We would need a way for client-side JS to fetch just the data, because the HTML page is already loaded and displayed; all that's needed is to inject more data into it. This is more the way that an infinite scrolling search engine shows results.

Depending on the approach we choose, I can provide some links or details about how it's done.

**Comment by smattingly** [comment]
@BroadusA This is your new assignment, and Megan will be managing this effort. Try to start learning what is involved. I am thinking about the technical details and will share more guidance as I can.

**Comment by BroadusA** [comment]
2/24- The first checkbox was completed. I Will be working on completing the next two checkboxes. @Spritte77

**Comment by Sprite411** [comment]
@BroadusA Ok seems you have some good progress, let me know if you need any assistance or have any questions

**Comment by BroadusA** [comment]
2/26- Still working through code for the onside scroll. @Spritte77.

**Comment by Sprite411** [comment]
Thank you for the update, keep me updated with any progress or questions you may have. @BroadusA

**Comment by BroadusA** [comment]
03/01- Would like some assistance for which file the code should be put. @Spritte77

**Comment by Sprite411** [comment]
If I understand correctly I would assume the code should go under index.html file under the visit folder. So the file path should be views > pages > visit > index.html. Though I would like confirmation before putting code into there @smattingly @BroadusA

**Comment by smattingly** [comment]
@BroadusA Yes, @Spritte77 is correct about that file. Later, we might break the code out into a new file of its own, but the client side code described in the second and third checkboxes go in that `index.html` for now.

**Comment by BroadusA** [comment]
3/5- after confirmation for the file. I have started writing the code.

**Comment by BroadusA** [comment]
3/8- Before I make changes to the original code. Will I mess up any current records for the NLC?

**Comment by smattingly** [comment]
I think you are referring to database records? I think you are running a GitPod workspace created directly from GitHub. Unless it has been manually reconfigured in specific ways (and I don't think you did that), it will use its own local copy of the database inside of GitPod.

**Comment by BroadusA** [comment]
03/17: Working through AJAX task.

**Comment by smattingly** [comment]
@BroadusA Can you make progress doing the AJAX yourself? (If so, that's fantastic, but I wouldn't be surprised if you want some help.) I believe @Weintraubm has been looking at AJAX in some other contexts. Or I can help if that's better. I can't get to the API part yet, but will as soon as I can.

**Comment by BroadusA** [comment]
03/22: Can I have some guidance for the next step in my task? OR even just to walk through AJAX.

**Comment by smattingly** [comment]
@BroadusA Yes, let's find a time to collaborate online with GitPod. Meanwhile, look at https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch, which we will use instead of AJAX.

**Comment by smattingly** [comment]
Today we learned some things.
1. Bad news: Angel lost her changes to this point, due to GitPod permissions not being set.
2. I found a very helpful example of what we're trying to do, which changes some of the details.

As a result, I am going to close this Issue and open a new one to give this tasks a fresh start.
