### ISSUE TITLE
Update NLC app dependencies

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#154]
`npm install` reports that 6 dependencies (listed in `package.json`) need updating due to security concerns, etc.
`npm audit` says that 3 can be automatically handled (run `npm audit fix`), but 3 will need manual review.

Most of this task boils down to:

- [x] In a Gitpod workspace, run `npm update --dev`
- [x] Then run `npm audit fix`
- [x] Thoroughly test the app to see nothing is broken, then commit the changes and push to GitHub.

We should then research the updates that `npm audit fix` tells us must be handled manually.

**Comment by smattingly** [comment]
@methenyk Turns out that node does need to be upgraded as server work, not changing app code/config. Same is true of npm and sails, although I think we can change that where sails is concerned. I will update the description (first comment) to reflect this.

**Comment by methenyk** [comment]
I am currently still doing some research on the three problems that need manual updates. I intend to know more about them within the upcoming days.

**Comment by methenyk** [comment]
I am still doing some research on 2 of the 3 manual updates. I should know more by the beginning of the next meeting.

**Comment by Weintraubm** [comment]
@methenyk what dependencies need manually updates? What are their errors?

**Comment by methenyk** [comment]
We have to low level errors and a high level error. One is the version of braces that we are running. It is an older version and is causing a Regular Expression Denial of Service. We need to update to version 2.3.1 or higher and this should fix the issue, this was the first low leveled error. The second one has to do with the version of minimist we have. It is throwing a prototype pollution error but this can be fixed by upgrading to versions 0.2.1, 1.2.3, or later. Our high risk error is a Denial of Service error, this can be caused by the Regular Expression Denial of error, but I am still looking into this.

**Comment by Weintraubm** [comment]
Very good just wanted a more detailed update for the github logging purposes carry on, let us know if you need help.

**Comment by methenyk** [comment]
With the Denial of Service error, is in mongodb. With an update to version 3.1.13 or later could fix this.

**Comment by smattingly** [comment]
I have no prior knowledge of "manually reviewing" audit findings. I found [this page/section](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities#security-vulnerabilities-found-requiring-manual-review) to be somewhat helpful, at least about concepts. Drawing on that, I think I understand that the situation is:

1. We have some indirect dependencies with issues that have been fixed (because it's telling us which versions will fix them), BUT
2. Our direct dependencies which need the packages from 1 have not yet been updated to use the fixed versions of their dependencies.

If I'm right, this suggests that:
1. Our direct dependencies will probably incorporate the fixes so that this eventually will be taken care of in a way that can be handled automatically.
2. The cost/benefit of us trying to manually fix it in the meantime is probably not worth it.

Suggestion: adapting the guidelines in the link above about mitigating circumstances, look at the details to see if we seem to be at especially high risk for any of these. Unless we are, it is probably best to let our direct dependencies update. We would just need to be diligent about running `npm audit` frequently to see if any of those fixes are available.

A couple of specific points: I'm not terribly worried about denial of service attacks on our system. I'm more concerned about data privacy. Our hosting setup is modest enough that there are probably many different ways that a DoS attack could succeed, if anyone wanted to dedicate the resources to targeting us.

Also, we are using (in production) a MongoDB cloud service (Atlas) using version 4.4.4. Either the "insecure version" 3.1.13 refers to our non-production environments or (more likely) that version is not for MongoDB itself, but for some library we use to connect to MongoDB (sails-mongo or similar).

**Comment by methenyk** [comment]
I have recently been looking at what professor Mattingly provided above. I have learned that some of the errors that we have are about updates to certain things. However, I feel that if we are not worried about them as much like professor Mattingly stated, should I be ready to push this to github? Or should I try to update these issues?

**Comment by smattingly** [comment]
@methenyk Let's move forward. Run the three qa scripts as we covered in today's meeting. Assuming there are no problems, you can commit your changes and try to sync to GitHub if you want. I haven't yet been able to resolve the permissions problem that stopped our colleague's sync, so you might get a permissions error too.

**Comment by methenyk** [comment]
I will be running the app to make sure that nothing appears wrong and I will be running the qa scripts gone over in class Wednesday. If I run into any problems I will make sure to comment and get assistance

**Comment by smattingly** [comment]
@methenyk When I created a new GitPod to research the cypress install problem that you had, I had no problem at all. So a completely fresh start makes everything good. That made me realize that we probably should have run `npm install` in your GitPod with the problem. In other words, I suspect that the dependency version numbers were updated in `package.json`, but those newer versions were not actually installed.

**Comment by methenyk** [comment]
@smattingly I'm sorry, I am slightly confused. I had ran npm install in my gitpod and the newer ones I had started to try and fix the problem. are you suggesting that I should have ran it again or am I misreading your statement above? Again, I am sorry but I am slightly confused.

**Comment by methenyk** [comment]
This issue is complete and finished. I have pushed my changes through to github and I believe Professor Mattingly has fixed the cypress issue I was having.

**Comment by smattingly** [comment]
@dewv/managers As I just did here, let's unassign staff members when their completed work is pushed to `dev`. Although the issue is not closed until it reaches `prod`, the staff member no longer has any work to perform on the issue.

**Comment by smattingly** [comment]
@dewv/managers If we get this change to production, it will unblock https://github.com/dewv/ops/issues/157. Please move changes on `dev` (including this one) to a new release for production. Let me know if you need an assist.

**Comment by smattingly** [comment]
Released as v2.5.5
