### ISSUE TITLE
Separate sports seasons

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#2]
Initial code does not distinguish fall vs spring sports. Need to do that.

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅  @smattingly  I made a commit a few minutes ago and mentioned you there as well (unsure if that also notifies you). I have a generalized start to the testing for seasons I would like you to review and please point me in the right direction for testing the functionality of the sorting to the HTML forum based on the season.

**Comment by codybroyles** [comment]
🍅         I recreated the test to do as I understood what we discussed after class today.

**Comment by codybroyles** [comment]
🍅

**Comment by smattingly** [comment]
@codybroyles Ok, after some research I think we need to go with the "two models" approach-- `Sport` will become `FallSport` and `SpringSport`. I was going to create an Issue but I think it really is this Issue as things have evolved. My guess is that you will keep working on this, but I'm putting @tydingsl in the loop because I need to get out of her way regarding task assignments.

**Comment by codybroyles** [comment]
alright

**Comment by codybroyles** [comment]
🍅
