### ISSUE TITLE
Check-in createform for Visit

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#22]
The Visit component must support creating new records (known as a "check in"). So, the visit folder will contain createForm.html, named in anticipation that the RestController can be used.

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 I closed because I missed something

**Comment by tydingsl** [comment]
@ricardmc99 can this issue be closed?

**Comment by ricardmc99** [comment]
@tydingsl yes
