### ISSUE TITLE
Check-in check-out

### ISSUE THREAD

**Issue by ricardmc99** [dewv/nlcAttendance#24]
How do we keep track of how long the user has been in the system? How does the timer work? @tydingsl

**Comment by smattingly** [comment]
In the current production system, the Visit record stores a check in timestamp, and a check out time stamp. The query that displays Visit data to staff computes the difference, to the nearest quarter hour (that's a user requirement).

There are additional details, and sails will impact things a bit. I'm going to document that in CONTRIBUTING.md when I can.
