### ISSUE TITLE
projectDocs

### ISSUE THREAD

**Issue by Evsus** [dewv/nlcAttendance#3]
Creation of projectDocs folder with general guidelines for management.

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅 Issue put on hold waiting for final decision on moving to CONTRIBUTION.md instead of projectDocs

**Comment by smattingly** [comment]
CONTRIBUTING.md is now in place. It covers all contents of former projectDocs folder, except for Risk Assessment. I will talk with @tydingsl about Risk Assessment.

**Comment by Evsus** [comment]
@tydingsl this issue is ready for closing if you're ready to be done with it.
