### ISSUE TITLE
OPERATIONS: State of the App

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#31]
The Application is growing rapidly and a quick update on how it looks from an operations perspective would yield valuable insight from a source other than the developers.

**Comment by tydingsl** [comment]
@alkhuwaylidr Any progress?

**Comment by alroaithih** [comment]
🍅

**Comment by alroaithih** [comment]
🍅 I have a technical issue in the server  when i try to check on nlcAttendance file

**Comment by alroaithih** [comment]
🍅 I found the file , it was under /var/www

**Comment by smattingly** [comment]
OBE: deployment platform changes are under consideration
