### ISSUE TITLE
logoutTimer.js

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#32]
In reference #15 and #23 ...really this will be used for the entire system since it runs in kiosk mode.
https://github.com/dewv/nlcAttendance/blob/master/CONTRIBUTING.md#student-check-in-check-out

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
In the old nlc_attendance, I don't understand the function logout(). Part is because I can't find the document "logout"
https://github.com/dewv/nlc_attendance/blob/5ddd3401a1a5284d9823ed1a188935d36198f0fa/public/javascripts/logoutTimer.js#L12

**Comment by tydingsl** [comment]
@ricardmc99 After talking to Owen, I believe this code is outdated. His original goal for this was to set a logout warning for the user if the page had been left inactive for too long after a person logged in. However, now that the page exits out to the main login after logging in or logging out, there is no reason to have a countdown to a logout for the user.

**Comment by tydingsl** [comment]
@ricardmc99 based off this link, the html makes it clear what it was for 
https://github.com/dewv/nlc_attendance/blob/5ddd3401a1a5284d9823ed1a188935d36198f0fa/views/logoutTimer.html

**Comment by tydingsl** [comment]
@ricardmc99 Can this issue be closed?

**Comment by tydingsl** [comment]
Issue became irrelevant
