### ISSUE TITLE
model validations

### ISSUE THREAD

**Issue by codybroyles** [dewv/nlcAttendance#4]
Implementing attribute vallidations in our current models.

**Comment by codybroyles** [comment]
🍅    I have added some validation into the Sails models, but we will need to handle them in our furls models.

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅

**Comment by codybroyles** [comment]
🍅  @tydingsl I talked to Prof Mattingly about this. Going to hold off until a need is more pressing here.

**Comment by tydingsl** [comment]
This issue became obsolete because it related only to sails.js, so I'm closing it.
