### ISSUE TITLE
Staff Visit View

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#41]
The view for staff to see what the visit model has collected

**Comment by Evsus** [comment]
🍅 updated nvm and npm and began setup

**Comment by Evsus** [comment]
🍅 x3 learned how sails routes traffic, planned the code structure, next will implement the code and push new page within the next 2 tomatoes

**Comment by Evsus** [comment]
🍅 Learned that the good way of going about this is to go ahead and update the routes file and the RESTcontroller so that the controller handles the database loading and configuring and the html page just sends and receives requests.  This feels like a more verbose way of handling the mmvece way of communicating and developing for the table easier.  Will this be okay? @tydingsl

**Comment by tydingsl** [comment]
👍

**Comment by Evsus** [comment]
🍅 worked more on the text input, I'd like for it to parse the text a bit for correctness before it gets passed to sails, and hopefully with the way sails works, it'll fill in some gaps that usually need added in by hand when querying databases on a front end

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅  Decided best to have a default pop up from the controller be the full view of visit and they can further filter the results by the post action.  So the first instance of the webpage pulls up a basic table return, and subsequent posts will pull the same webpage with a different query.  The query format is commented into the visit view.

**Comment by Evsus** [comment]
🍅 Will need to see what the controller does when it gets the table.  Might need to research more on table displays in javascript/html

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅 cleaning up some formatting

**Comment by Evsus** [comment]
🍅 fixed route format.  Handle page design

**Comment by Evsus** [comment]
🍅 getting queries to work

**Comment by Evsus** [comment]
🍅 appending to restControl

**Comment by Evsus** [comment]
🍅 small updates to restController still need to figure out how to pass table (will probably have to procedurally generate a table) to html page.  if query method from sails doesn't return anything friendly.

**Comment by Evsus** [comment]
🍅

**Comment by tydingsl** [comment]
@Evsus Can I get a progress update?

**Comment by Evsus** [comment]
Sure, Have the controller working and visit playing nice, fleshing it out now to display everything and request data.

**Comment by Evsus** [comment]
🍅  Does query and populates tables with information.  currently no information to populate with.  Considering this one done.  Should probably have an issue prepared for when this view and the visit model is available for integration.

**Comment by tydingsl** [comment]
Pull request #56 was merged and the issue was completed
