### ISSUE TITLE
View for staff to export visit model to a spreadsheet

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#42]
#41 is the precursor to this.  The information from this visit should be translated to a spreadsheet via a new page.

**Comment by tydingsl** [comment]
@Evsus When do you think you will begin work on this?

**Comment by Evsus** [comment]
when the previous one is clean and working, I'm just assigned to it since they are part of a series.

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
Are we looking to export solely .xlsx since everyone should have Microsoft Excel?

**Comment by tydingsl** [comment]
@Evsus No, use .csv

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
note: the regular view has{visit#, student name, check in, check out, visit length, purpose, purpose achieved, tutoring (courses), comments, checkout estimated (Y,N)}

dump: {regular view{}, and more™️}

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅  Download button works, performing linting and tests now

**Comment by Evsus** [comment]
htmlhint and mocha ran, but lint and coverage would not run in my environment.  Will Consult with @smattingly  tomorrow and sort that out. 🍅
