### ISSUE TITLE
Staff Register this Browser

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#43]
A very simple form for registering a browser for nlc

**Comment by brosekerg** [comment]
May i be assigned to this issue?

**Comment by tydingsl** [comment]
#48 pull request merged

**Comment by tydingsl** [comment]
This issue was thought to have been completed, but the StaffRegisterBrowser.js should be an html file and, when the file name was changed, it no longer passes the test. Please make the required changes so that this file is an html and passes the tests for a pull request. #52

**Comment by brosekerg** [comment]
🍅

**Comment by tydingsl** [comment]
Merged pull request
