### ISSUE TITLE
Landing Page for Staff

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#44]
Should include links to all staff forms: edit form, visit list, visit spreadsheet, and register browser

**Comment by Emreyildirim1284** [comment]
I am sorry, I didn't quite get the assignment. Can you please be little bit more specific?

**Comment by Emreyildirim1284** [comment]
Am I creating the HTML page when staff logs in? Like the first screen that they see? And I am assuming they have access to see those 4 things you listed so I am creating a page that has links to each file?

**Comment by Emreyildirim1284** [comment]
🍅

**Comment by tydingsl** [comment]
@Emreyildirim1284 yes, this is the first page when a staff member logs in. They should have access to these 4 forms

**Comment by tydingsl** [comment]
@Emreyildirim1284 You should have access to the register browser and the edit form. The other 2 forms are being worked on currently

**Comment by Emreyildirim1284** [comment]
Okay, my code is ready. I will finish it and push it as soon as other 2 forms are done.

**Comment by Emreyildirim1284** [comment]
🍅

**Comment by tydingsl** [comment]
merged pull request
