### ISSUE TITLE
Add `afterPopulateOne` call

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#49]
The `populateOne` helper should check to see if the model passed to it defines a ~~`postPopulate`~~ `afterPopulateOne` function, and if so, call it.

@codybroyles Note name change, to follow Sails lifecycle hooks after/before and use full name of `populateOne`

**Comment by smattingly** [comment]
@codybroyles I have pushed this on branch `issue49`. Suggest you merge that branch into yours. I don't want to PR into master, because the change creates a code statement that is not tested by my code, dropping us below the code coverage threshold. Rather than concoct a test, your model that defines the function should cause the test coverage to take care of itself. (I did test this change with temporary dummy test code that I removed before commit.)

**Comment by smattingly** [comment]
@codybroyles I think this could be closed? If you agree, please close it.

**Comment by codybroyles** [comment]
I agree it can be closed as I have had the changes merged for a while now. Closes #49
