### ISSUE TITLE
Names in lookup tables should be unique

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#5]
https://github.com/dewv/nlcAttendance/blob/b1750278b22050195e9cf3a84db93623d5c2a8cc/api/models/ClassRank.js#L3
Please add `unique: true` to the properties.

**Comment by ricardmc99** [comment]
🍅 Just change it in in this documents:
https://github.com/dewv/nlcAttendance/blob/wip-ricard/api/models/ClassRank.js
https://github.com/dewv/nlcAttendance/blob/wip-ricard/api/models/Majors.js
https://github.com/dewv/nlcAttendance/blob/wip-ricard/api/models/ResidentialStatus.js
Does true goes with " " ?

**Comment by smattingly** [comment]
I don't understand the question. Also, I think that having models for residential status and class rank is probably overkill-- I think we would be okay hard-coding those into the form. Didn't we discuss that?
(We definitely *do* want a model for `Major`, but please tweak the name-- we want to consistently use singular, not plural, model names.)
