### ISSUE TITLE
CSS for NLC

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#57]
Make the application look more professional using CSS

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅

**Comment by ricardmc99** [comment]
🍅 finish with the staff header

**Comment by smattingly** [comment]
@bakejice Right now, the "show stopper" problem is that you cannot see all screen contents when, for example, there are too many sports or too many majors. 
A less critical issue: layout of screens with banner messages could use some improvement.

**Comment by smattingly** [comment]
Why didn't this auto close?
