### ISSUE TITLE
Fix visit view portion of rest controller

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#58]
Fix visit view portion of the rest controller

**Comment by Evsus** [comment]
Found issue with REST Controller will correct once visit download is complete

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
🍅

**Comment by Evsus** [comment]
restful api is being followed better, however there will need to be a new helper to facilitate the rest controller's ability to be more generic.  But that is a task for later.  Cleaning up code and submitting to master.  

Further: "View" needs pagination. this is accomplished by:
 ```await model.find().paginate(pageNum, pageSize);```
so pagination will be a part of the query helper.

**Comment by Evsus** [comment]
🍅

**Comment by alroaithih** [comment]
can i get assign 🍅

**Comment by smattingly** [comment]
OBE
