### ISSUE TITLE
Define Sails.js

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#6]
Declare useful information that is relevant to our usage of Sails.js. For instance: starting sails, closing sails, how the models plug into sails, etc. Write documentation for quick lookup specifically for our organization.

**Comment by smattingly** [comment]
@tydingsl I volunteer; feel free to assign this to me (and others, too, if appropriate). I have just merged all the new sails stuff onto the `master` branch, including new `README` files in each of the major folders (models, controllers, views, helpers); that is a start. I will get to some of the other things you mentioned as soon as I can.

**Comment by smattingly** [comment]
Just pushed update to `master` that creates `CONTRIBUTING.md` (see [this](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)) and [other documentation](https://dewv.github.io/nlcAttendance/).
