### ISSUE TITLE
NLC 

### ISSUE THREAD

**Issue by alroaithih** [dewv/nlcAttendance#60]

**Comment by alroaithih** [comment]
🍅 I made sure the nlcAttendance file is active

**Comment by alroaithih** [comment]
🍅 its run under npm install

**Comment by alroaithih** [comment]
🍅 I have been getting errors when i try to install nvm

**Comment by alroaithih** [comment]
🍅 nlcAttendance under cd/var/www

**Comment by alroaithih** [comment]
![Capturedddd](https://user-images.githubusercontent.com/35502208/57145892-24b4eb00-6d92-11e9-878c-3c884d0d4be0.PNG)

**Comment by smattingly** [comment]
?
