### ISSUE TITLE
Catalog Information from nlc2

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#7]
Look through the old nlc2 repository for useful information that can be translated into sails.js for the new repository nlcAttendance. Compile it into a single document for reference.

**Comment by Evsus** [comment]
🍅 Short descriptions of what the original NLC had 

| Student | Description |
| -------- | ----------- |
| id | Autogenerate |
| Username | string |
| Firstname | string |
| Lastname | string |
| AcademicRank | choice of 5 | 
| MajorOne | Choice from majors |
| MajorTwo | Choice from majors |
| ResidentialStatus | Boolean (resident or commutor) |
| sports | FK, Choice from sports | 

|  Staff | Description | 
| ----- | ------------ | 
| id | Autogenerate | 
| UserName | String | 
| FirstName | String | 
| LastName | String | 
| SlpInstructor | Boolean | 

# Sports 
| Winter | Spring | 
| ------- | ------ | 
| TBD     | TBD    |


Next is to hold on to this until we can move it into a Project documentation file/folder

**Comment by Evsus** [comment]
@smattingly Would it be proper to move these tables into CONTRIBUTING.md?

**Comment by Evsus** [comment]
@tydingsl I believe this is ready to close without any pulls.
