### ISSUE TITLE
Create Model Database

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#8]
Using the information from issue #7 and any further data deemed important, build the database for us to use with Sails.js for nlc Attendance.

**Comment by tydingsl** [comment]
@smattingly This issue is more so that we have the information to give to Sails so that it can build the database. This is just providing the info to generate the table

**Comment by smattingly** [comment]
Here is a quick messy dump of the information that I think you are looking for. When I can, I will put this in CONTRIBUTING.md in more sails language.

Staff: need username, firstName, lastName, and these can be just like in existing Student model. Also need `isSlpInstructor` which is a boolean defaulting to `false`.

Visit: here is partial dump of current table definition. Names should become camelCase not snake_case, the _yn should become boolean, and other things need tweaked to. More on that later.
```
| student_key            | int(11)      | NO   |     | NULL              |                |
| check_in               | timestamp    | NO   |     | CURRENT_TIMESTAMP |                |
| check_out              | timestamp    | YES  |     | NULL              |                |
| tutoring               | varchar(255) | YES  |     | NULL              |                |
| location               | varchar(255) | NO   |     | NULL              |                |
| purpose                | varchar(255) | NO   |     | NULL              |                |
| purpose_achieved       | char(1)      | YES  |     | NULL              |                |
| comments               | varchar(255) | YES  |     | NULL              |                |
| check_out_estimated_yn | char(1)      | YES  |     | NULL              |                |
```

**Comment by smattingly** [comment]
@tydingsl I believe that there are now Issues for each individual model, some completed, others assigned. Can this be closed?
