### ISSUE TITLE
Fix security alerts for ESLint dependencies

### ISSUE THREAD

**Issue by smattingly** [dewv/nlcAttendance#90]
GitHub's dependabot recently created two security alerts in this repo, for two dependencies of the ESLint package that we use.

These alerts need to be resolved, probably by upgrading to newer versions of the dependencies.

This will require some knowledge about how a project's dependencies are listed in the `package.json` file, and how acceptable versions are indicated there. Research this as needed.

Also note that our project uses ESLint only for development purposes (it is a code quality checker). `package.json` allows a distinction between normal dependencies and "devDependencies", which are packages needed only in the development environment. Several of our project's dependencies could/should be moved to devDependencies, and it makes sense to do that as part of this task. (We had the idea that we would want to run test tools, etc. in the production environment too, but it turns out that's not such a helpful idea.)

**Comment by Weintraubm** [comment]
@smattingly ran npm outdated and installed all major updates and attempted to push

**Comment by smattingly** [comment]
@Weintraubm Ok, you successfully pushed to the master branch. 
Ordinarily, there are automated checks that verify all tests are passing and >= 95% of code is covered by tests, otherwise pushes to master are rejected. The checks are currently disabled because late changes to 2.0.0 (introducing sails) broke the tests, and we wanted to release based on manual testing.

Ideally you would have run tests manually to ensure the dependency changes broke nothing. It's OK here if you didn't because we're not headed anywhere with master changes at the moment.
But please do this: address the two newest security alerts for dependencies as you did the others, and then run the automated tests. Also please look at semver.org to understand why some of the changes are more risky than others.

With that complete, we can close this issue.
